### ISSUE TITLE
Emacs Lisp Coding Conventions

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Wilfred/loop.el#1]
Please, take a look at **[Emacs Lisp Coding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html)**. The relevant extract:

> - If you need Common Lisp extensions, use the `cl-lib` library rather than the old `cl` library. The latter does not use a clean namespace (i.e., its definitions do not start with a ‘`cl-`’ prefix). If your package loads `cl` at run time, that could cause name clashes for users who don't use that package.
>   - There is no problem with using the `cl` package at _compile_ time, with `(eval-when-compile (require 'cl))`. That's sufficient for using the macros in the `cl` package, because the compiler expands them before generating the byte-code. It is still better to use the more modern `cl-lib` in this case, though.

**Comment by AdrieanKhisbe** [comment]
@Wilfred I can take care of that if you want ;:)

**Comment by Wilfred** [comment]
I'm always open to PRs.
