### ISSUE TITLE
dolist and dotimes are not part of cl-lib

### ISSUE THREAD

**Issue by wasamasa** [Wilfred/loop.el#3]
See `subr.el`.  These can be used just fine in existing code, `cl-dolist` and `cl-dotimes` merely provide you the ability of breaking out early.

**Comment by wasamasa** [comment]
I mean the alternatives section in the README.

**Comment by Wilfred** [comment]
Ah, gotcha. How's this version?

**Comment by wasamasa** [comment]
Looking good.
